services:
  envoy:
    image: envoyproxy/envoy:v1.18.3
    container_name: envoy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8001:8001"
      - "80:80"
    networks:
      - multitrabajos

  ocelot:
    image: ocelot.docker
    build: ./multisecuritygateway/multitrabajo-gateway/multitrabajo-gateway
    container_name: ocelot
    ports:
      - "8085:8085"
    networks:
      - multitrabajos

  multisecurity:
    image: multisecurity
    build: ./multisecurity
    container_name: multisecurity
    ports:
      - "8079:80"
    networks:
      - multitrabajos

  multicuenta:
    image: multicuenta
    build: ./multisecuritycuenta/multitrabajos-cuenta/multitrabajos-cuenta
    container_name: multicuenta
    ports:
      - "8080:8080"
    networks:
      - multitrabajos

  multideposito:
    image: multideposito
    build: ./multisecuritydeposito/multitrabajo-deposito/multitrabajo-deposito
    container_name: multideposito
    ports:
      - "8081:80"
    networks:
      - multitrabajos

  multiretiro:
    image: multiretiro
    build: ./multisecurityretiro/multitrabajo-retiro/multitrabajo-retiro
    container_name: multiretiro
    ports:
      - "8082:80"
    networks:
      - multitrabajos

  multinotification:
    image: multinotification
    build: ./multisecuritynotificacion/multitrabajos-quinaopa-notificacion/multitrabajos-quinaopa-notificacion
    container_name: multinotification
    ports:
      - "8083:80"
    networks:
      - multitrabajos

  multihistory:
    image: multihistory
    build: ./multisecurityhistory/multitrabajos-history/multitrabajos-history
    container_name: multihistory
    ports:
      - "8084:80"
    networks:
      - multitrabajos

networks:
  multitrabajos:
    external: true