services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: cordillera123
    ports:
      - "27018:27017"  # Mapea el puerto 27018 en tu host al puerto 27017 del contenedor
    networks:
      - multitrabajos

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: cordillera123
      POSTGRES_DB: db_account2
    ports:
      - "5432:5432"
    networks:
      - multitrabajos

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: cordillera123
      MYSQL_DATABASE: dbSecurity
      MYSQL_USER: root
      MYSQL_PASSWORD: cordillera123
    ports:
      - "3307:3306"
    networks:
      - multitrabajos

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver1
    environment:
      SA_PASSWORD: Cordillera123
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    networks:
      - multitrabajos

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: cordillera123
      MYSQL_DATABASE: dbSecurity
    ports:
      - "3306:3306"
    networks:
      - multitrabajos

  rabbitmq:
    image: rabbitmq:management
    container_name: service-event
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: Cordillera123
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"  # Puerto para la consola de administración de RabbitMQ
    networks:
      - multitrabajos
  envoy:
    image: envoyproxy/envoy:v1.21.0
    container_name: envoy
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8001:8001"
      - "8002:8002"
    networks:
      - multitrabajos

  ocelot:
    image: ocelot.docker
    build: ./multisecuritygateway/multitrabajo-gateway/multitrabajo-gateway
    container_name: ocelot
    ports:
      - "8085:8085"
    networks:
      - multitrabajos

  multisecurity:
    image: multisecurity
    build: ./multisecurity
    container_name: multisecurity
    ports:
      - "8079:8079"
    networks:
      - multitrabajos

  multicuenta:
    image: multicuenta
    build: ./multisecuritycuenta/multitrabajos-cuenta/multitrabajos-cuenta
    container_name: multicuenta
    ports:
      - "8080:8080"
    networks:
      - multitrabajos

  multideposito:
    image: multideposito
    build: ./multisecuritydeposito/multitrabajo-deposito/multitrabajo-deposito
    container_name: multideposito
    ports:
      - "8081:8081"
    networks:
      - multitrabajos

  multiretiro:
    image: multiretiro
    build: ./multisecurityretiro/multitrabajo-retiro/multitrabajo-retiro
    container_name: multiretiro
    ports:
      - "8082:8082"
    networks:
      - multitrabajos

  multinotification:
    image: multinotificacion
    build: ./multisecuritynotificacion/multitrabajos-quinaopa-notificacion/multitrabajos-quinaopa-notificacion
    container_name: multinotificacion
    ports:
      - "8083:8083"
    networks:
      - multitrabajos

  multihistory:
    image: multihistory
    build: ./multisecurityhistory/multitrabajos-history/multitrabajos-history
    container_name: multihistory
    ports:
      - "8084:8084"
    networks:
      - multitrabajos

networks:
  multitrabajos:
    external: true