services:
  rabbitmq:
    image: rabbitmq:management
    container_name: service-event
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: Cordillera123
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"  # Puerto para la consola de administración de RabbitMQ
    networks:
      - multitrabajos
  envoy:
    image: envoyproxy/envoy:v1.21.0
    container_name: envoy
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8001:8001"
      - "8002:8002"
    networks:
      - multitrabajos

  multisecurity:
    image: multisecurity
    build: ./multisecurity
    container_name: multisecurity
    ports:
      - "8079:8079"
    networks:
      - multitrabajos

  multicuenta:
    image: multicuenta
    build: ./multisecuritycuenta/multitrabajos-cuenta/multitrabajos-cuenta
    container_name: multicuenta
    ports:
      - "8080:8080"
    networks:
      - multitrabajos

  multideposito:
    image: multideposito
    build: ./multisecuritydeposito/multitrabajo-deposito/multitrabajo-deposito
    container_name: multideposito
    ports:
      - "8081:8081"
    networks:
      - multitrabajos

  multiretiro:
    image: multiretiro
    build: ./multisecurityretiro/multitrabajo-retiro/multitrabajo-retiro
    container_name: multiretiro
    ports:
      - "8082:8082"
    networks:
      - multitrabajos

  multinotification:
    image: multinotificacion
    build: ./multisecuritynotificacion/multitrabajos-quinaopa-notificacion/multitrabajos-quinaopa-notificacion
    container_name: multinotificacion
    ports:
      - "8083:8083"
    networks:
      - multitrabajos

  multihistory:
    image: multihistory
    build: ./multisecurityhistory/multitrabajos-history/multitrabajos-history
    container_name: multihistory
    ports:
      - "8084:8084"
    networks:
      - multitrabajos

networks:
  multitrabajos:
    external: true